paths:
  data_dir: data/benchmark_encoders
  figures_dir: Figures

format:
  output: gif #'gif' for png & gif, 'pdf' for pdf

parameters:
  epsilon: 0.2
  alpha: 0.95
  lr_confidence: 0.9
  seed: 1444

data:
  dataset_path: results.parquet
  experimental_factors:
    dataset: null
    model: "LR"
    tuning: "no"
    scoring: "ACC"
  target: "cv_score"
  alternatives: "encoder"

sampling:
  sample_size: 10
  disjoint: true
  replace: false
